// <auto-generated />
namespace MyShop.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AddMigrationAddBasket : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMigrationAddBasket));
        
        string IMigrationMetadata.Id
        {
            get { return "201910260443387_Add-Migration AddBasket"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
